// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendAgentEventReducer from "../append_agent_event_reducer.js";
import ApproveToolCallReducer from "../approve_tool_call_reducer.js";
import CreateSessionReducer from "../create_session_reducer.js";
import HeartbeatPresenceReducer from "../heartbeat_presence_reducer.js";
import JoinPresenceReducer from "../join_presence_reducer.js";
import LeavePresenceReducer from "../leave_presence_reducer.js";
import ProposeToolCallReducer from "../propose_tool_call_reducer.js";
import RejectToolCallReducer from "../reject_tool_call_reducer.js";
import SendMessageReducer from "../send_message_reducer.js";
import UpdateSessionStatusReducer from "../update_session_status_reducer.js";

export type AppendAgentEventParams = __Infer<typeof AppendAgentEventReducer>;
export type ApproveToolCallParams = __Infer<typeof ApproveToolCallReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type HeartbeatPresenceParams = __Infer<typeof HeartbeatPresenceReducer>;
export type JoinPresenceParams = __Infer<typeof JoinPresenceReducer>;
export type LeavePresenceParams = __Infer<typeof LeavePresenceReducer>;
export type ProposeToolCallParams = __Infer<typeof ProposeToolCallReducer>;
export type RejectToolCallParams = __Infer<typeof RejectToolCallReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type UpdateSessionStatusParams = __Infer<typeof UpdateSessionStatusReducer>;

