// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().name("session_id"),
  seq: __t.u64(),
  authorType: __t.string().name("author_type"),
  authorName: __t.string().name("author_name"),
  eventType: __t.string().name("event_type"),
  payload: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
