// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  clientId: __t.string().primaryKey().name("client_id"),
  sessionId: __t.string().name("session_id"),
  authorName: __t.string().name("author_name"),
  role: __t.string(),
  color: __t.string(),
  connectedAt: __t.timestamp().name("connected_at"),
  lastSeen: __t.timestamp().name("last_seen"),
});
