// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  toolName: __t.string().name("tool_name"),
  argsJson: __t.string().name("args_json"),
  resultJson: __t.option(__t.string()).name("result_json"),
  status: __t.string(),
  requiresApproval: __t.bool().name("requires_approval"),
});
