// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Event = __t.object("Event", {
  sessionId: __t.string(),
  seq: __t.u64(),
  authorType: __t.string(),
  authorName: __t.string(),
  eventType: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Session = __t.object("Session", {
  id: __t.string(),
  title: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const SessionPresence = __t.object("SessionPresence", {
  clientId: __t.string(),
  sessionId: __t.string(),
  authorName: __t.string(),
  role: __t.string(),
  color: __t.string(),
  connectedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type SessionPresence = __Infer<typeof SessionPresence>;

export const ToolInvocation = __t.object("ToolInvocation", {
  id: __t.string(),
  sessionId: __t.string(),
  toolName: __t.string(),
  argsJson: __t.string(),
  resultJson: __t.option(__t.string()),
  status: __t.string(),
  requiresApproval: __t.bool(),
});
export type ToolInvocation = __Infer<typeof ToolInvocation>;

